# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build miles`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t miles`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system miles && \
          adduser --system -G miles miles

COPY dist/miles miles
RUN chown -R miles:miles .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix miles --omit=dev -f install

CMD [ "node", "miles" ]
